version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: eventservicedb_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: eventservicesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - event_net

  redis:
    image: redis:7-alpine
    container_name: eventdb_redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - event_net

volumes:
  postgres_data:
  redis_data:

networks:
  event_net:
    driver: bridge
