version: "3.9"

services:
  db:
    image: postgis/postgis:17-3.4
    container_name: postgis-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eventservicedb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - event_net

  redis:
    image: redis:7-alpine
    container_name: eventdb_redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - event_net

volumes:
  pgdata:
  redis_data:

networks:
  event_net:
    driver: bridge
